export const site = {
  name: "GulbargaHomes",
  shortName: "Gulbarga Homes",
  domain: "gulbargahomes.com",
  url: "https://gulbargahomes.com",
  city: "Gulbarga",
  cityOfficial: "Kalaburagi",
  cityDisplay: "Gulbarga (Kalaburagi)",
  region: "Karnataka",
  tagline: "Find Your Perfect Home in Gulbarga",
  homeSeoTitle:
    "Houses, Flats & Plots for Rent and Sale in Gulbarga (Kalaburagi)",
  description:
    "GulbargaHomes is the curated real estate platform for Gulbarga (Kalaburagi) — rental houses, 1/2/3 BHK flats, independent homes, villas and residential plots for sale across Sedam Road, Azadpur, Biddapur Colony, Kusnoor, Jewargi Road and more. Verified details on Vastu, parking, water supply, bachelor and family preferences.",
  keywords: [
    "houses for rent in gulbarga",
    "flats for rent in kalaburagi",
    "2 bhk rent gulbarga",
    "plots for sale in gulbarga",
    "house for sale kalaburagi",
    "residential plots sedam road",
    "rental house gulbarga",
    "property in kalaburagi",
    "gulbarga homes",
    "kalaburagi real estate",
  ],
  phone: "+918123450725",
  phoneDisplay: "+91 81234 50725",
  whatsapp: "918123450725",
  email: "hello@gulbargahomes.com",
  geo: {
    latitude: 17.3297,
    longitude: 76.8343,
  },
  localities: [
    "Sedam Road",
    "Azadpur",
    "Biddapur Colony",
    "Jewargi Road",
    "Kusnoor",
    "Kalnoor",
    "Shahbazar",
    "Super Market",
    "Station Area",
    "Aiwan-E-Shahi",
    "MSK Mill Road",
    "University Area",
    "Timmapuri",
    "Court Road",
    "Ring Road",
    "Aland Road",
    "Humnabad Road",
    "Brahmapur",
  ],
} as const;
