export const siteContacts = [
  {
    phone: "+918123450725",
    phoneDisplay: "+91 81234 50725",
    whatsapp: "918123450725",
  },
  {
    phone: "+918431395255",
    phoneDisplay: "+91 84313 95255",
    whatsapp: "918431395255",
  },
] as const;

export const site = {
  name: "GulbargaHomes",
  shortName: "Gulbarga Homes",
  domain: "gulbargahomes.com",
  url: "https://gulbargahomes.com",
  city: "Gulbarga",
  cityOfficial: "Kalaburagi",
  cityDisplay: "Gulbarga (Kalaburagi)",
  region: "Karnataka",
  tagline: "Find Your Perfect Home in Gulbarga",
  homeSeoTitle:
    "Houses, Flats & Plots for Rent and Sale in Gulbarga (Kalaburagi)",
  description:
    "GulbargaHomes is the curated real estate platform for Gulbarga (Kalaburagi) — rental houses, 1/2/3 BHK flats, independent homes, villas, commercial space and residential plots for sale across High Court, Sedam Road, Azadpur, Biddapur Colony, Kusnoor, Jewargi Road and more. Verified details on Vastu, parking, water supply, bachelor and family preferences.",
  keywords: [
    "houses for rent in gulbarga",
    "flats for rent in kalaburagi",
    "2 bhk rent gulbarga",
    "plots for sale in gulbarga",
    "house for sale kalaburagi",
    "residential plots sedam road",
    "rental house gulbarga",
    "property in kalaburagi",
    "gulbarga homes",
    "kalaburagi real estate",
  ],
  phone: siteContacts[0].phone,
  phoneDisplay: siteContacts[0].phoneDisplay,
  whatsapp: siteContacts[0].whatsapp,
  contacts: siteContacts,
  phonesDisplay: siteContacts.map((contact) => contact.phoneDisplay).join(" · "),
  email: "hello@gulbargahomes.com",
  geo: {
    latitude: 17.3297,
    longitude: 76.8343,
  },
  localities: [
    "Sedam Road",
    "Azadpur",
    "Biddapur Colony",
    "Jewargi Road",
    "Kusnoor",
    "Kalnoor",
    "Shahbazar",
    "Super Market",
    "Station Area",
    "Aiwan-E-Shahi",
    "MSK Mill Road",
    "University Area",
    "Timmapuri",
    "Court Road",
    "High Court",
    "Sai Nagar",
    "Shahabad Road",
    "Ring Road",
    "Aland Road",
    "Humnabad Road",
    "Brahmapur",
  ],
} as const;
